/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAgentRegistry,
  IAgentRegistryInterface,
} from "../../IRelayVault.sol/IAgentRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "agentId",
        type: "address",
      },
    ],
    name: "deregister",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "agentId",
        type: "address",
      },
    ],
    name: "getAgent",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "agentId",
            type: "address",
          },
          {
            internalType: "bytes32[]",
            name: "capabilities",
            type: "bytes32[]",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "basePrice",
                type: "uint256",
              },
              {
                internalType: "address",
                name: "currency",
                type: "address",
              },
              {
                internalType: "enum IAgentRegistry.PricingType",
                name: "pricingType",
                type: "uint8",
              },
            ],
            internalType: "struct IAgentRegistry.PricingModel",
            name: "pricingModel",
            type: "tuple",
          },
          {
            internalType: "uint256",
            name: "reputationScore",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "vaultAddress",
            type: "address",
          },
          {
            internalType: "enum IAgentRegistry.AgentStatus",
            name: "status",
            type: "uint8",
          },
          {
            internalType: "uint256",
            name: "registeredAt",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "totalTasksCompleted",
            type: "uint256",
          },
        ],
        internalType: "struct IAgentRegistry.AgentInfo",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "agentId",
        type: "address",
      },
    ],
    name: "getVaultAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32[]",
        name: "capabilities",
        type: "bytes32[]",
      },
      {
        components: [
          {
            internalType: "uint256",
            name: "basePrice",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "currency",
            type: "address",
          },
          {
            internalType: "enum IAgentRegistry.PricingType",
            name: "pricingType",
            type: "uint8",
          },
        ],
        internalType: "struct IAgentRegistry.PricingModel",
        name: "pricingModel",
        type: "tuple",
      },
      {
        internalType: "bytes",
        name: "routingConfig",
        type: "bytes",
      },
    ],
    name: "register",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "agentId",
        type: "address",
      },
      {
        internalType: "string",
        name: "reason",
        type: "string",
      },
    ],
    name: "suspend",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "agentId",
        type: "address",
      },
      {
        internalType: "bytes32[]",
        name: "capabilities",
        type: "bytes32[]",
      },
    ],
    name: "updateCapabilities",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "agentId",
        type: "address",
      },
      {
        components: [
          {
            internalType: "uint256",
            name: "basePrice",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "currency",
            type: "address",
          },
          {
            internalType: "enum IAgentRegistry.PricingType",
            name: "pricingType",
            type: "uint8",
          },
        ],
        internalType: "struct IAgentRegistry.PricingModel",
        name: "pricingModel",
        type: "tuple",
      },
    ],
    name: "updatePricing",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "agentId",
        type: "address",
      },
      {
        internalType: "int256",
        name: "deltaScore",
        type: "int256",
      },
      {
        internalType: "bytes32",
        name: "taskId",
        type: "bytes32",
      },
    ],
    name: "updateReputation",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IAgentRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IAgentRegistryInterface {
    return new Interface(_abi) as IAgentRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAgentRegistry {
    return new Contract(address, _abi, runner) as unknown as IAgentRegistry;
  }
}
