/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  INegotiationEngine,
  INegotiationEngineInterface,
} from "../../IRelayVault.sol/INegotiationEngine";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "bidId",
        type: "bytes32",
      },
    ],
    name: "acceptBid",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "bidId",
        type: "bytes32",
      },
    ],
    name: "cancelBid",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "bidId",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "newPrice",
        type: "uint256",
      },
    ],
    name: "counterBid",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "bidId",
        type: "bytes32",
      },
    ],
    name: "getBid",
    outputs: [
      {
        components: [
          {
            internalType: "bytes32",
            name: "bidId",
            type: "bytes32",
          },
          {
            internalType: "string",
            name: "taskSpecCID",
            type: "string",
          },
          {
            internalType: "address",
            name: "initiator",
            type: "address",
          },
          {
            internalType: "address",
            name: "targetAgent",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "price",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "ttlBlocks",
            type: "uint256",
          },
          {
            internalType: "enum INegotiationEngine.BidState",
            name: "state",
            type: "uint8",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "price",
                type: "uint256",
              },
              {
                internalType: "address",
                name: "by",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "at",
                type: "uint256",
              },
            ],
            internalType: "struct INegotiationEngine.CounterBid[]",
            name: "counterHistory",
            type: "tuple[]",
          },
          {
            internalType: "uint256",
            name: "createdAt",
            type: "uint256",
          },
        ],
        internalType: "struct INegotiationEngine.Bid",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "taskSpecCID",
        type: "string",
      },
      {
        internalType: "address",
        name: "targetAgent",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "price",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "ttlBlocks",
        type: "uint256",
      },
    ],
    name: "submitBid",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class INegotiationEngine__factory {
  static readonly abi = _abi;
  static createInterface(): INegotiationEngineInterface {
    return new Interface(_abi) as INegotiationEngineInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): INegotiationEngine {
    return new Contract(address, _abi, runner) as unknown as INegotiationEngine;
  }
}
