/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ITaskEscrow,
  ITaskEscrowInterface,
} from "../../IRelayVault.sol/ITaskEscrow";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "bidId",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "deadlineBlocks",
        type: "uint256",
      },
    ],
    name: "lockFunds",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "escrowId",
        type: "bytes32",
      },
      {
        internalType: "string",
        name: "evidenceCID",
        type: "string",
      },
    ],
    name: "openDispute",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "escrowId",
        type: "bytes32",
      },
      {
        internalType: "uint8",
        name: "resolutionOutcome",
        type: "uint8",
      },
    ],
    name: "resolveDispute",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "escrowId",
        type: "bytes32",
      },
      {
        internalType: "string",
        name: "completionProof",
        type: "string",
      },
    ],
    name: "verifyAndRelease",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ITaskEscrow__factory {
  static readonly abi = _abi;
  static createInterface(): ITaskEscrowInterface {
    return new Interface(_abi) as ITaskEscrowInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ITaskEscrow {
    return new Contract(address, _abi, runner) as unknown as ITaskEscrow;
  }
}
