/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface TaskEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "activeEscrows"
      | "approveLargeTask"
      | "disputeResolver"
      | "escrows"
      | "governance"
      | "largeTaskApproved"
      | "lockFunds"
      | "negotiation"
      | "openDispute"
      | "owner"
      | "registry"
      | "resolveDispute"
      | "setEngines"
      | "verifyAndRelease"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DisputeOpened"
      | "EscrowRefunded"
      | "FundsLocked"
      | "FundsReleased"
      | "TaskCompleted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "activeEscrows",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "approveLargeTask",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "disputeResolver",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "escrows", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "governance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "largeTaskApproved",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lockFunds",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "negotiation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "openDispute",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "resolveDispute",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setEngines",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyAndRelease",
    values: [BytesLike, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "activeEscrows",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveLargeTask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disputeResolver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "escrows", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "governance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "largeTaskApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lockFunds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "negotiation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "openDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "resolveDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setEngines", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifyAndRelease",
    data: BytesLike
  ): Result;
}

export namespace DisputeOpenedEvent {
  export type InputTuple = [escrowId: BytesLike, evidenceCID: string];
  export type OutputTuple = [escrowId: string, evidenceCID: string];
  export interface OutputObject {
    escrowId: string;
    evidenceCID: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowRefundedEvent {
  export type InputTuple = [escrowId: BytesLike, amount: BigNumberish];
  export type OutputTuple = [escrowId: string, amount: bigint];
  export interface OutputObject {
    escrowId: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsLockedEvent {
  export type InputTuple = [
    escrowId: BytesLike,
    bidId: BytesLike,
    payer: AddressLike,
    receiver: AddressLike,
    amount: BigNumberish,
    deadline: BigNumberish
  ];
  export type OutputTuple = [
    escrowId: string,
    bidId: string,
    payer: string,
    receiver: string,
    amount: bigint,
    deadline: bigint
  ];
  export interface OutputObject {
    escrowId: string;
    bidId: string;
    payer: string;
    receiver: string;
    amount: bigint;
    deadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsReleasedEvent {
  export type InputTuple = [
    escrowId: BytesLike,
    amount: BigNumberish,
    vaultAddress: AddressLike
  ];
  export type OutputTuple = [
    escrowId: string,
    amount: bigint,
    vaultAddress: string
  ];
  export interface OutputObject {
    escrowId: string;
    amount: bigint;
    vaultAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskCompletedEvent {
  export type InputTuple = [
    escrowId: BytesLike,
    completionProof: string,
    method: BigNumberish
  ];
  export type OutputTuple = [
    escrowId: string,
    completionProof: string,
    method: bigint
  ];
  export interface OutputObject {
    escrowId: string;
    completionProof: string;
    method: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TaskEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): TaskEscrow;
  waitForDeployment(): Promise<this>;

  interface: TaskEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  activeEscrows: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  approveLargeTask: TypedContractMethod<
    [escrowId: BytesLike],
    [void],
    "nonpayable"
  >;

  disputeResolver: TypedContractMethod<[], [string], "view">;

  escrows: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, string, bigint, bigint, bigint, bigint] & {
        escrowId: string;
        bidId: string;
        payer: string;
        receiver: string;
        amount: bigint;
        deadlineBlock: bigint;
        state: bigint;
        verificationMethod: bigint;
      }
    ],
    "view"
  >;

  governance: TypedContractMethod<[], [string], "view">;

  largeTaskApproved: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  lockFunds: TypedContractMethod<
    [bidId: BytesLike, amount: BigNumberish, deadlineBlocks: BigNumberish],
    [void],
    "nonpayable"
  >;

  negotiation: TypedContractMethod<[], [string], "view">;

  openDispute: TypedContractMethod<
    [escrowId: BytesLike, evidenceCID: string],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  registry: TypedContractMethod<[], [string], "view">;

  resolveDispute: TypedContractMethod<
    [escrowId: BytesLike, resolutionOutcome: BigNumberish],
    [void],
    "nonpayable"
  >;

  setEngines: TypedContractMethod<
    [
      _negotiation: AddressLike,
      _disputeResolver: AddressLike,
      _governance: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  verifyAndRelease: TypedContractMethod<
    [escrowId: BytesLike, completionProof: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "activeEscrows"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "approveLargeTask"
  ): TypedContractMethod<[escrowId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "disputeResolver"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "escrows"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, string, bigint, bigint, bigint, bigint] & {
        escrowId: string;
        bidId: string;
        payer: string;
        receiver: string;
        amount: bigint;
        deadlineBlock: bigint;
        state: bigint;
        verificationMethod: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "governance"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "largeTaskApproved"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "lockFunds"
  ): TypedContractMethod<
    [bidId: BytesLike, amount: BigNumberish, deadlineBlocks: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "negotiation"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "openDispute"
  ): TypedContractMethod<
    [escrowId: BytesLike, evidenceCID: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "resolveDispute"
  ): TypedContractMethod<
    [escrowId: BytesLike, resolutionOutcome: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setEngines"
  ): TypedContractMethod<
    [
      _negotiation: AddressLike,
      _disputeResolver: AddressLike,
      _governance: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyAndRelease"
  ): TypedContractMethod<
    [escrowId: BytesLike, completionProof: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DisputeOpened"
  ): TypedContractEvent<
    DisputeOpenedEvent.InputTuple,
    DisputeOpenedEvent.OutputTuple,
    DisputeOpenedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowRefunded"
  ): TypedContractEvent<
    EscrowRefundedEvent.InputTuple,
    EscrowRefundedEvent.OutputTuple,
    EscrowRefundedEvent.OutputObject
  >;
  getEvent(
    key: "FundsLocked"
  ): TypedContractEvent<
    FundsLockedEvent.InputTuple,
    FundsLockedEvent.OutputTuple,
    FundsLockedEvent.OutputObject
  >;
  getEvent(
    key: "FundsReleased"
  ): TypedContractEvent<
    FundsReleasedEvent.InputTuple,
    FundsReleasedEvent.OutputTuple,
    FundsReleasedEvent.OutputObject
  >;
  getEvent(
    key: "TaskCompleted"
  ): TypedContractEvent<
    TaskCompletedEvent.InputTuple,
    TaskCompletedEvent.OutputTuple,
    TaskCompletedEvent.OutputObject
  >;

  filters: {
    "DisputeOpened(bytes32,string)": TypedContractEvent<
      DisputeOpenedEvent.InputTuple,
      DisputeOpenedEvent.OutputTuple,
      DisputeOpenedEvent.OutputObject
    >;
    DisputeOpened: TypedContractEvent<
      DisputeOpenedEvent.InputTuple,
      DisputeOpenedEvent.OutputTuple,
      DisputeOpenedEvent.OutputObject
    >;

    "EscrowRefunded(bytes32,uint256)": TypedContractEvent<
      EscrowRefundedEvent.InputTuple,
      EscrowRefundedEvent.OutputTuple,
      EscrowRefundedEvent.OutputObject
    >;
    EscrowRefunded: TypedContractEvent<
      EscrowRefundedEvent.InputTuple,
      EscrowRefundedEvent.OutputTuple,
      EscrowRefundedEvent.OutputObject
    >;

    "FundsLocked(bytes32,bytes32,address,address,uint256,uint256)": TypedContractEvent<
      FundsLockedEvent.InputTuple,
      FundsLockedEvent.OutputTuple,
      FundsLockedEvent.OutputObject
    >;
    FundsLocked: TypedContractEvent<
      FundsLockedEvent.InputTuple,
      FundsLockedEvent.OutputTuple,
      FundsLockedEvent.OutputObject
    >;

    "FundsReleased(bytes32,uint256,address)": TypedContractEvent<
      FundsReleasedEvent.InputTuple,
      FundsReleasedEvent.OutputTuple,
      FundsReleasedEvent.OutputObject
    >;
    FundsReleased: TypedContractEvent<
      FundsReleasedEvent.InputTuple,
      FundsReleasedEvent.OutputTuple,
      FundsReleasedEvent.OutputObject
    >;

    "TaskCompleted(bytes32,string,uint8)": TypedContractEvent<
      TaskCompletedEvent.InputTuple,
      TaskCompletedEvent.OutputTuple,
      TaskCompletedEvent.OutputObject
    >;
    TaskCompleted: TypedContractEvent<
      TaskCompletedEvent.InputTuple,
      TaskCompletedEvent.OutputTuple,
      TaskCompletedEvent.OutputObject
    >;
  };
}
