/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface DisputeResolverInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "assignArbitrators"
      | "disputes"
      | "finalizeResolution"
      | "openDispute"
      | "owner"
      | "registry"
      | "setTaskEscrow"
      | "submitEvidence"
      | "taskEscrow"
      | "voteResolution"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ArbitratorVoted"
      | "DisputeCreated"
      | "DisputeResolved"
      | "EvidenceSubmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "assignArbitrators",
    values: [BytesLike, AddressLike[]]
  ): string;
  encodeFunctionData(functionFragment: "disputes", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "finalizeResolution",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "openDispute",
    values: [BytesLike, string, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setTaskEscrow",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitEvidence",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "taskEscrow",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "voteResolution",
    values: [BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "assignArbitrators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "disputes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "finalizeResolution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "openDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setTaskEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitEvidence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "taskEscrow", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "voteResolution",
    data: BytesLike
  ): Result;
}

export namespace ArbitratorVotedEvent {
  export type InputTuple = [
    disputeId: BytesLike,
    arbitrator: AddressLike,
    resolution: BigNumberish
  ];
  export type OutputTuple = [
    disputeId: string,
    arbitrator: string,
    resolution: bigint
  ];
  export interface OutputObject {
    disputeId: string;
    arbitrator: string;
    resolution: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeCreatedEvent {
  export type InputTuple = [
    disputeId: BytesLike,
    escrowId: BytesLike,
    claimant: AddressLike
  ];
  export type OutputTuple = [
    disputeId: string,
    escrowId: string,
    claimant: string
  ];
  export interface OutputObject {
    disputeId: string;
    escrowId: string;
    claimant: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeResolvedEvent {
  export type InputTuple = [
    disputeId: BytesLike,
    finalResolution: BigNumberish
  ];
  export type OutputTuple = [disputeId: string, finalResolution: bigint];
  export interface OutputObject {
    disputeId: string;
    finalResolution: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EvidenceSubmittedEvent {
  export type InputTuple = [
    disputeId: BytesLike,
    by: AddressLike,
    evidenceCID: string
  ];
  export type OutputTuple = [
    disputeId: string,
    by: string,
    evidenceCID: string
  ];
  export interface OutputObject {
    disputeId: string;
    by: string;
    evidenceCID: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DisputeResolver extends BaseContract {
  connect(runner?: ContractRunner | null): DisputeResolver;
  waitForDeployment(): Promise<this>;

  interface: DisputeResolverInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  assignArbitrators: TypedContractMethod<
    [disputeId: BytesLike, arbitratorsList: AddressLike[]],
    [void],
    "nonpayable"
  >;

  disputes: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, string, bigint, bigint, bigint] & {
        disputeId: string;
        escrowId: string;
        claimant: string;
        respondent: string;
        finalResolution: bigint;
        state: bigint;
        voteDeadlineBlock: bigint;
      }
    ],
    "view"
  >;

  finalizeResolution: TypedContractMethod<
    [disputeId: BytesLike],
    [void],
    "nonpayable"
  >;

  openDispute: TypedContractMethod<
    [escrowId: BytesLike, evidenceCID: string, respondent: AddressLike],
    [string],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  registry: TypedContractMethod<[], [string], "view">;

  setTaskEscrow: TypedContractMethod<
    [_taskEscrow: AddressLike],
    [void],
    "nonpayable"
  >;

  submitEvidence: TypedContractMethod<
    [disputeId: BytesLike, evidenceCID: string],
    [void],
    "nonpayable"
  >;

  taskEscrow: TypedContractMethod<[], [string], "view">;

  voteResolution: TypedContractMethod<
    [disputeId: BytesLike, resolution: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "assignArbitrators"
  ): TypedContractMethod<
    [disputeId: BytesLike, arbitratorsList: AddressLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "disputes"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, string, bigint, bigint, bigint] & {
        disputeId: string;
        escrowId: string;
        claimant: string;
        respondent: string;
        finalResolution: bigint;
        state: bigint;
        voteDeadlineBlock: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "finalizeResolution"
  ): TypedContractMethod<[disputeId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "openDispute"
  ): TypedContractMethod<
    [escrowId: BytesLike, evidenceCID: string, respondent: AddressLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setTaskEscrow"
  ): TypedContractMethod<[_taskEscrow: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitEvidence"
  ): TypedContractMethod<
    [disputeId: BytesLike, evidenceCID: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "taskEscrow"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "voteResolution"
  ): TypedContractMethod<
    [disputeId: BytesLike, resolution: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ArbitratorVoted"
  ): TypedContractEvent<
    ArbitratorVotedEvent.InputTuple,
    ArbitratorVotedEvent.OutputTuple,
    ArbitratorVotedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeCreated"
  ): TypedContractEvent<
    DisputeCreatedEvent.InputTuple,
    DisputeCreatedEvent.OutputTuple,
    DisputeCreatedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeResolved"
  ): TypedContractEvent<
    DisputeResolvedEvent.InputTuple,
    DisputeResolvedEvent.OutputTuple,
    DisputeResolvedEvent.OutputObject
  >;
  getEvent(
    key: "EvidenceSubmitted"
  ): TypedContractEvent<
    EvidenceSubmittedEvent.InputTuple,
    EvidenceSubmittedEvent.OutputTuple,
    EvidenceSubmittedEvent.OutputObject
  >;

  filters: {
    "ArbitratorVoted(bytes32,address,uint8)": TypedContractEvent<
      ArbitratorVotedEvent.InputTuple,
      ArbitratorVotedEvent.OutputTuple,
      ArbitratorVotedEvent.OutputObject
    >;
    ArbitratorVoted: TypedContractEvent<
      ArbitratorVotedEvent.InputTuple,
      ArbitratorVotedEvent.OutputTuple,
      ArbitratorVotedEvent.OutputObject
    >;

    "DisputeCreated(bytes32,bytes32,address)": TypedContractEvent<
      DisputeCreatedEvent.InputTuple,
      DisputeCreatedEvent.OutputTuple,
      DisputeCreatedEvent.OutputObject
    >;
    DisputeCreated: TypedContractEvent<
      DisputeCreatedEvent.InputTuple,
      DisputeCreatedEvent.OutputTuple,
      DisputeCreatedEvent.OutputObject
    >;

    "DisputeResolved(bytes32,uint8)": TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;
    DisputeResolved: TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;

    "EvidenceSubmitted(bytes32,address,string)": TypedContractEvent<
      EvidenceSubmittedEvent.InputTuple,
      EvidenceSubmittedEvent.OutputTuple,
      EvidenceSubmittedEvent.OutputObject
    >;
    EvidenceSubmitted: TypedContractEvent<
      EvidenceSubmittedEvent.InputTuple,
      EvidenceSubmittedEvent.OutputTuple,
      EvidenceSubmittedEvent.OutputObject
    >;
  };
}
