/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace IAgentRegistry {
  export type PricingModelStruct = {
    basePrice: BigNumberish;
    currency: AddressLike;
    pricingType: BigNumberish;
  };

  export type PricingModelStructOutput = [
    basePrice: bigint,
    currency: string,
    pricingType: bigint
  ] & { basePrice: bigint; currency: string; pricingType: bigint };

  export type AgentInfoStruct = {
    agentId: AddressLike;
    capabilities: BytesLike[];
    pricingModel: IAgentRegistry.PricingModelStruct;
    reputationScore: BigNumberish;
    vaultAddress: AddressLike;
    status: BigNumberish;
    registeredAt: BigNumberish;
    totalTasksCompleted: BigNumberish;
  };

  export type AgentInfoStructOutput = [
    agentId: string,
    capabilities: string[],
    pricingModel: IAgentRegistry.PricingModelStructOutput,
    reputationScore: bigint,
    vaultAddress: string,
    status: bigint,
    registeredAt: bigint,
    totalTasksCompleted: bigint
  ] & {
    agentId: string;
    capabilities: string[];
    pricingModel: IAgentRegistry.PricingModelStructOutput;
    reputationScore: bigint;
    vaultAddress: string;
    status: bigint;
    registeredAt: bigint;
    totalTasksCompleted: bigint;
  };
}

export interface IAgentRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "deregister"
      | "getAgent"
      | "getVaultAddress"
      | "register"
      | "suspend"
      | "updateCapabilities"
      | "updatePricing"
      | "updateReputation"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "deregister",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVaultAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "register",
    values: [BytesLike[], IAgentRegistry.PricingModelStruct, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "suspend",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateCapabilities",
    values: [AddressLike, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePricing",
    values: [AddressLike, IAgentRegistry.PricingModelStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "updateReputation",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "deregister", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getAgent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getVaultAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "suspend", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateCapabilities",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePricing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateReputation",
    data: BytesLike
  ): Result;
}

export interface IAgentRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IAgentRegistry;
  waitForDeployment(): Promise<this>;

  interface: IAgentRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deregister: TypedContractMethod<[agentId: AddressLike], [void], "nonpayable">;

  getAgent: TypedContractMethod<
    [agentId: AddressLike],
    [IAgentRegistry.AgentInfoStructOutput],
    "view"
  >;

  getVaultAddress: TypedContractMethod<
    [agentId: AddressLike],
    [string],
    "view"
  >;

  register: TypedContractMethod<
    [
      capabilities: BytesLike[],
      pricingModel: IAgentRegistry.PricingModelStruct,
      routingConfig: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  suspend: TypedContractMethod<
    [agentId: AddressLike, reason: string],
    [void],
    "nonpayable"
  >;

  updateCapabilities: TypedContractMethod<
    [agentId: AddressLike, capabilities: BytesLike[]],
    [void],
    "nonpayable"
  >;

  updatePricing: TypedContractMethod<
    [agentId: AddressLike, pricingModel: IAgentRegistry.PricingModelStruct],
    [void],
    "nonpayable"
  >;

  updateReputation: TypedContractMethod<
    [agentId: AddressLike, deltaScore: BigNumberish, taskId: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deregister"
  ): TypedContractMethod<[agentId: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAgent"
  ): TypedContractMethod<
    [agentId: AddressLike],
    [IAgentRegistry.AgentInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVaultAddress"
  ): TypedContractMethod<[agentId: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "register"
  ): TypedContractMethod<
    [
      capabilities: BytesLike[],
      pricingModel: IAgentRegistry.PricingModelStruct,
      routingConfig: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "suspend"
  ): TypedContractMethod<
    [agentId: AddressLike, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateCapabilities"
  ): TypedContractMethod<
    [agentId: AddressLike, capabilities: BytesLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updatePricing"
  ): TypedContractMethod<
    [agentId: AddressLike, pricingModel: IAgentRegistry.PricingModelStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateReputation"
  ): TypedContractMethod<
    [agentId: AddressLike, deltaScore: BigNumberish, taskId: BytesLike],
    [void],
    "nonpayable"
  >;

  filters: {};
}
