/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace INegotiationEngine {
  export type CounterBidStruct = {
    price: BigNumberish;
    by: AddressLike;
    at: BigNumberish;
  };

  export type CounterBidStructOutput = [
    price: bigint,
    by: string,
    at: bigint
  ] & { price: bigint; by: string; at: bigint };

  export type BidStruct = {
    bidId: BytesLike;
    taskSpecCID: string;
    initiator: AddressLike;
    targetAgent: AddressLike;
    price: BigNumberish;
    ttlBlocks: BigNumberish;
    state: BigNumberish;
    counterHistory: INegotiationEngine.CounterBidStruct[];
    createdAt: BigNumberish;
  };

  export type BidStructOutput = [
    bidId: string,
    taskSpecCID: string,
    initiator: string,
    targetAgent: string,
    price: bigint,
    ttlBlocks: bigint,
    state: bigint,
    counterHistory: INegotiationEngine.CounterBidStructOutput[],
    createdAt: bigint
  ] & {
    bidId: string;
    taskSpecCID: string;
    initiator: string;
    targetAgent: string;
    price: bigint;
    ttlBlocks: bigint;
    state: bigint;
    counterHistory: INegotiationEngine.CounterBidStructOutput[];
    createdAt: bigint;
  };
}

export interface INegotiationEngineInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptBid"
      | "cancelBid"
      | "counterBid"
      | "getBid"
      | "submitBid"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "acceptBid",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelBid",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "counterBid",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getBid", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "submitBid",
    values: [string, AddressLike, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "acceptBid", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cancelBid", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "counterBid", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getBid", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "submitBid", data: BytesLike): Result;
}

export interface INegotiationEngine extends BaseContract {
  connect(runner?: ContractRunner | null): INegotiationEngine;
  waitForDeployment(): Promise<this>;

  interface: INegotiationEngineInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptBid: TypedContractMethod<[bidId: BytesLike], [void], "nonpayable">;

  cancelBid: TypedContractMethod<[bidId: BytesLike], [void], "nonpayable">;

  counterBid: TypedContractMethod<
    [bidId: BytesLike, newPrice: BigNumberish],
    [void],
    "nonpayable"
  >;

  getBid: TypedContractMethod<
    [bidId: BytesLike],
    [INegotiationEngine.BidStructOutput],
    "view"
  >;

  submitBid: TypedContractMethod<
    [
      taskSpecCID: string,
      targetAgent: AddressLike,
      price: BigNumberish,
      ttlBlocks: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptBid"
  ): TypedContractMethod<[bidId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelBid"
  ): TypedContractMethod<[bidId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "counterBid"
  ): TypedContractMethod<
    [bidId: BytesLike, newPrice: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getBid"
  ): TypedContractMethod<
    [bidId: BytesLike],
    [INegotiationEngine.BidStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "submitBid"
  ): TypedContractMethod<
    [
      taskSpecCID: string,
      targetAgent: AddressLike,
      price: BigNumberish,
      ttlBlocks: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  filters: {};
}
