/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ITaskEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "lockFunds"
      | "openDispute"
      | "resolveDispute"
      | "verifyAndRelease"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "lockFunds",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "openDispute",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveDispute",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyAndRelease",
    values: [BytesLike, string]
  ): string;

  decodeFunctionResult(functionFragment: "lockFunds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "openDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyAndRelease",
    data: BytesLike
  ): Result;
}

export interface ITaskEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): ITaskEscrow;
  waitForDeployment(): Promise<this>;

  interface: ITaskEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  lockFunds: TypedContractMethod<
    [bidId: BytesLike, amount: BigNumberish, deadlineBlocks: BigNumberish],
    [void],
    "nonpayable"
  >;

  openDispute: TypedContractMethod<
    [escrowId: BytesLike, evidenceCID: string],
    [void],
    "nonpayable"
  >;

  resolveDispute: TypedContractMethod<
    [escrowId: BytesLike, resolutionOutcome: BigNumberish],
    [void],
    "nonpayable"
  >;

  verifyAndRelease: TypedContractMethod<
    [escrowId: BytesLike, completionProof: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "lockFunds"
  ): TypedContractMethod<
    [bidId: BytesLike, amount: BigNumberish, deadlineBlocks: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "openDispute"
  ): TypedContractMethod<
    [escrowId: BytesLike, evidenceCID: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resolveDispute"
  ): TypedContractMethod<
    [escrowId: BytesLike, resolutionOutcome: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyAndRelease"
  ): TypedContractMethod<
    [escrowId: BytesLike, completionProof: string],
    [void],
    "nonpayable"
  >;

  filters: {};
}
