/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace IVaultWallet {
  export type SplitRecipientStruct = {
    recipient: AddressLike;
    bps: BigNumberish;
  };

  export type SplitRecipientStructOutput = [recipient: string, bps: bigint] & {
    recipient: string;
    bps: bigint;
  };
}

export interface IVaultWalletInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "claimUnlocked"
      | "getBalance"
      | "initialize"
      | "receivePayment"
      | "setRouting"
      | "withdraw"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "claimUnlocked",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "receivePayment",
    values: [BigNumberish, BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setRouting",
    values: [IVaultWallet.SplitRecipientStruct[], BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "claimUnlocked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBalance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "receivePayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setRouting", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export interface IVaultWallet extends BaseContract {
  connect(runner?: ContractRunner | null): IVaultWallet;
  waitForDeployment(): Promise<this>;

  interface: IVaultWalletInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  claimUnlocked: TypedContractMethod<[], [void], "nonpayable">;

  getBalance: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        available: bigint;
        locked: bigint;
        total: bigint;
      }
    ],
    "view"
  >;

  initialize: TypedContractMethod<
    [_owner: AddressLike, _taskEscrow: AddressLike, _currency: AddressLike],
    [void],
    "nonpayable"
  >;

  receivePayment: TypedContractMethod<
    [amount: BigNumberish, taskId: BytesLike, payer: AddressLike],
    [void],
    "nonpayable"
  >;

  setRouting: TypedContractMethod<
    [
      splits: IVaultWallet.SplitRecipientStruct[],
      lockBps: BigNumberish,
      holdBps: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<
    [amount: BigNumberish, recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "claimUnlocked"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getBalance"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        available: bigint;
        locked: bigint;
        total: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [_owner: AddressLike, _taskEscrow: AddressLike, _currency: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "receivePayment"
  ): TypedContractMethod<
    [amount: BigNumberish, taskId: BytesLike, payer: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setRouting"
  ): TypedContractMethod<
    [
      splits: IVaultWallet.SplitRecipientStruct[],
      lockBps: BigNumberish,
      holdBps: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [amount: BigNumberish, recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  filters: {};
}
