/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace IAgentRegistry {
  export type PricingModelStruct = {
    basePrice: BigNumberish;
    currency: AddressLike;
    pricingType: BigNumberish;
  };

  export type PricingModelStructOutput = [
    basePrice: bigint,
    currency: string,
    pricingType: bigint
  ] & { basePrice: bigint; currency: string; pricingType: bigint };

  export type AgentInfoStruct = {
    agentId: AddressLike;
    capabilities: BytesLike[];
    pricingModel: IAgentRegistry.PricingModelStruct;
    reputationScore: BigNumberish;
    vaultAddress: AddressLike;
    status: BigNumberish;
    registeredAt: BigNumberish;
    totalTasksCompleted: BigNumberish;
  };

  export type AgentInfoStructOutput = [
    agentId: string,
    capabilities: string[],
    pricingModel: IAgentRegistry.PricingModelStructOutput,
    reputationScore: bigint,
    vaultAddress: string,
    status: bigint,
    registeredAt: bigint,
    totalTasksCompleted: bigint
  ] & {
    agentId: string;
    capabilities: string[];
    pricingModel: IAgentRegistry.PricingModelStructOutput;
    reputationScore: bigint;
    vaultAddress: string;
    status: bigint;
    registeredAt: bigint;
    totalTasksCompleted: bigint;
  };
}

export interface AgentRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "agentAddresses"
      | "agentCount"
      | "agentVaults"
      | "agents"
      | "deregister"
      | "disputeResolver"
      | "getAgent"
      | "getAllAgents"
      | "getVaultAddress"
      | "owner"
      | "register"
      | "setRoles"
      | "suspend"
      | "taskEscrow"
      | "updateCapabilities"
      | "updatePricing"
      | "updateReputation"
      | "vaultToAgent"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentDeregistered"
      | "AgentRegistered"
      | "AgentSuspended"
      | "CapabilitiesUpdated"
      | "ReputationUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "agentAddresses",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "agentCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "agentVaults",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "agents", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "deregister",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "disputeResolver",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllAgents",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getVaultAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "register",
    values: [BytesLike[], IAgentRegistry.PricingModelStruct, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setRoles",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "suspend",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "taskEscrow",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateCapabilities",
    values: [AddressLike, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePricing",
    values: [AddressLike, IAgentRegistry.PricingModelStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "updateReputation",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vaultToAgent",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "agentAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "agentCount", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "agentVaults",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "agents", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deregister", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "disputeResolver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAgent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllAgents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVaultAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setRoles", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "suspend", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "taskEscrow", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateCapabilities",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePricing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateReputation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vaultToAgent",
    data: BytesLike
  ): Result;
}

export namespace AgentDeregisteredEvent {
  export type InputTuple = [agentId: AddressLike];
  export type OutputTuple = [agentId: string];
  export interface OutputObject {
    agentId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentRegisteredEvent {
  export type InputTuple = [
    agentId: AddressLike,
    vaultAddress: AddressLike,
    capabilities: BytesLike[],
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    agentId: string,
    vaultAddress: string,
    capabilities: string[],
    timestamp: bigint
  ];
  export interface OutputObject {
    agentId: string;
    vaultAddress: string;
    capabilities: string[];
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentSuspendedEvent {
  export type InputTuple = [agentId: AddressLike, reason: string];
  export type OutputTuple = [agentId: string, reason: string];
  export interface OutputObject {
    agentId: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CapabilitiesUpdatedEvent {
  export type InputTuple = [agentId: AddressLike, capabilities: BytesLike[]];
  export type OutputTuple = [agentId: string, capabilities: string[]];
  export interface OutputObject {
    agentId: string;
    capabilities: string[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReputationUpdatedEvent {
  export type InputTuple = [
    agentId: AddressLike,
    previousScore: BigNumberish,
    newScore: BigNumberish,
    trigger: BytesLike
  ];
  export type OutputTuple = [
    agentId: string,
    previousScore: bigint,
    newScore: bigint,
    trigger: string
  ];
  export interface OutputObject {
    agentId: string;
    previousScore: bigint;
    newScore: bigint;
    trigger: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): AgentRegistry;
  waitForDeployment(): Promise<this>;

  interface: AgentRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agentAddresses: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  agentCount: TypedContractMethod<[], [bigint], "view">;

  agentVaults: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  agents: TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        string,
        IAgentRegistry.PricingModelStructOutput,
        bigint,
        string,
        bigint,
        bigint,
        bigint
      ] & {
        agentId: string;
        pricingModel: IAgentRegistry.PricingModelStructOutput;
        reputationScore: bigint;
        vaultAddress: string;
        status: bigint;
        registeredAt: bigint;
        totalTasksCompleted: bigint;
      }
    ],
    "view"
  >;

  deregister: TypedContractMethod<[agentId: AddressLike], [void], "nonpayable">;

  disputeResolver: TypedContractMethod<[], [string], "view">;

  getAgent: TypedContractMethod<
    [agentId: AddressLike],
    [IAgentRegistry.AgentInfoStructOutput],
    "view"
  >;

  getAllAgents: TypedContractMethod<
    [],
    [IAgentRegistry.AgentInfoStructOutput[]],
    "view"
  >;

  getVaultAddress: TypedContractMethod<
    [agentId: AddressLike],
    [string],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  register: TypedContractMethod<
    [
      capabilities: BytesLike[],
      pricingModel: IAgentRegistry.PricingModelStruct,
      routingConfig: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  setRoles: TypedContractMethod<
    [_taskEscrow: AddressLike, _disputeResolver: AddressLike],
    [void],
    "nonpayable"
  >;

  suspend: TypedContractMethod<
    [agentId: AddressLike, reason: string],
    [void],
    "nonpayable"
  >;

  taskEscrow: TypedContractMethod<[], [string], "view">;

  updateCapabilities: TypedContractMethod<
    [agentId: AddressLike, capabilities: BytesLike[]],
    [void],
    "nonpayable"
  >;

  updatePricing: TypedContractMethod<
    [agentId: AddressLike, pricingModel: IAgentRegistry.PricingModelStruct],
    [void],
    "nonpayable"
  >;

  updateReputation: TypedContractMethod<
    [agentId: AddressLike, deltaScore: BigNumberish, taskId: BytesLike],
    [void],
    "nonpayable"
  >;

  vaultToAgent: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agentAddresses"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "agentCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "agentVaults"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "agents"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        string,
        IAgentRegistry.PricingModelStructOutput,
        bigint,
        string,
        bigint,
        bigint,
        bigint
      ] & {
        agentId: string;
        pricingModel: IAgentRegistry.PricingModelStructOutput;
        reputationScore: bigint;
        vaultAddress: string;
        status: bigint;
        registeredAt: bigint;
        totalTasksCompleted: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "deregister"
  ): TypedContractMethod<[agentId: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "disputeResolver"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getAgent"
  ): TypedContractMethod<
    [agentId: AddressLike],
    [IAgentRegistry.AgentInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAllAgents"
  ): TypedContractMethod<[], [IAgentRegistry.AgentInfoStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getVaultAddress"
  ): TypedContractMethod<[agentId: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "register"
  ): TypedContractMethod<
    [
      capabilities: BytesLike[],
      pricingModel: IAgentRegistry.PricingModelStruct,
      routingConfig: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setRoles"
  ): TypedContractMethod<
    [_taskEscrow: AddressLike, _disputeResolver: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "suspend"
  ): TypedContractMethod<
    [agentId: AddressLike, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "taskEscrow"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "updateCapabilities"
  ): TypedContractMethod<
    [agentId: AddressLike, capabilities: BytesLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updatePricing"
  ): TypedContractMethod<
    [agentId: AddressLike, pricingModel: IAgentRegistry.PricingModelStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateReputation"
  ): TypedContractMethod<
    [agentId: AddressLike, deltaScore: BigNumberish, taskId: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "vaultToAgent"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;

  getEvent(
    key: "AgentDeregistered"
  ): TypedContractEvent<
    AgentDeregisteredEvent.InputTuple,
    AgentDeregisteredEvent.OutputTuple,
    AgentDeregisteredEvent.OutputObject
  >;
  getEvent(
    key: "AgentRegistered"
  ): TypedContractEvent<
    AgentRegisteredEvent.InputTuple,
    AgentRegisteredEvent.OutputTuple,
    AgentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "AgentSuspended"
  ): TypedContractEvent<
    AgentSuspendedEvent.InputTuple,
    AgentSuspendedEvent.OutputTuple,
    AgentSuspendedEvent.OutputObject
  >;
  getEvent(
    key: "CapabilitiesUpdated"
  ): TypedContractEvent<
    CapabilitiesUpdatedEvent.InputTuple,
    CapabilitiesUpdatedEvent.OutputTuple,
    CapabilitiesUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ReputationUpdated"
  ): TypedContractEvent<
    ReputationUpdatedEvent.InputTuple,
    ReputationUpdatedEvent.OutputTuple,
    ReputationUpdatedEvent.OutputObject
  >;

  filters: {
    "AgentDeregistered(address)": TypedContractEvent<
      AgentDeregisteredEvent.InputTuple,
      AgentDeregisteredEvent.OutputTuple,
      AgentDeregisteredEvent.OutputObject
    >;
    AgentDeregistered: TypedContractEvent<
      AgentDeregisteredEvent.InputTuple,
      AgentDeregisteredEvent.OutputTuple,
      AgentDeregisteredEvent.OutputObject
    >;

    "AgentRegistered(address,address,bytes32[],uint256)": TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;
    AgentRegistered: TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;

    "AgentSuspended(address,string)": TypedContractEvent<
      AgentSuspendedEvent.InputTuple,
      AgentSuspendedEvent.OutputTuple,
      AgentSuspendedEvent.OutputObject
    >;
    AgentSuspended: TypedContractEvent<
      AgentSuspendedEvent.InputTuple,
      AgentSuspendedEvent.OutputTuple,
      AgentSuspendedEvent.OutputObject
    >;

    "CapabilitiesUpdated(address,bytes32[])": TypedContractEvent<
      CapabilitiesUpdatedEvent.InputTuple,
      CapabilitiesUpdatedEvent.OutputTuple,
      CapabilitiesUpdatedEvent.OutputObject
    >;
    CapabilitiesUpdated: TypedContractEvent<
      CapabilitiesUpdatedEvent.InputTuple,
      CapabilitiesUpdatedEvent.OutputTuple,
      CapabilitiesUpdatedEvent.OutputObject
    >;

    "ReputationUpdated(address,uint256,uint256,bytes32)": TypedContractEvent<
      ReputationUpdatedEvent.InputTuple,
      ReputationUpdatedEvent.OutputTuple,
      ReputationUpdatedEvent.OutputObject
    >;
    ReputationUpdated: TypedContractEvent<
      ReputationUpdatedEvent.InputTuple,
      ReputationUpdatedEvent.OutputTuple,
      ReputationUpdatedEvent.OutputObject
    >;
  };
}
