/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace IVaultWallet {
  export type SplitRecipientStruct = {
    recipient: AddressLike;
    bps: BigNumberish;
  };

  export type SplitRecipientStructOutput = [recipient: string, bps: bigint] & {
    recipient: string;
    bps: bigint;
  };
}

export interface VaultWalletInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "availableBalance"
      | "claimUnlocked"
      | "currency"
      | "currentHoldBps"
      | "currentLockBps"
      | "currentSplits"
      | "getBalance"
      | "getRouting"
      | "initialize"
      | "initialized"
      | "lockedBalance"
      | "owner"
      | "receivePayment"
      | "setRouting"
      | "taskEscrow"
      | "timeLocks"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "PaymentProcessed" | "RoutingUpdated" | "Withdrawal"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "availableBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimUnlocked",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "currency", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "currentHoldBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentLockBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentSplits",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRouting",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialized",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lockedBalance",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "receivePayment",
    values: [BigNumberish, BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setRouting",
    values: [IVaultWallet.SplitRecipientStruct[], BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "taskEscrow",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "timeLocks",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "availableBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimUnlocked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "currency", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "currentHoldBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentLockBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentSplits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBalance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getRouting", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initialized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lockedBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "receivePayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setRouting", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "taskEscrow", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "timeLocks", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace PaymentProcessedEvent {
  export type InputTuple = [
    taskId: BytesLike,
    totalAmount: BigNumberish,
    lockAmount: BigNumberish,
    holdAmount: BigNumberish
  ];
  export type OutputTuple = [
    taskId: string,
    totalAmount: bigint,
    lockAmount: bigint,
    holdAmount: bigint
  ];
  export interface OutputObject {
    taskId: string;
    totalAmount: bigint;
    lockAmount: bigint;
    holdAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoutingUpdatedEvent {
  export type InputTuple = [
    vault: AddressLike,
    lockBps: BigNumberish,
    holdBps: BigNumberish
  ];
  export type OutputTuple = [vault: string, lockBps: bigint, holdBps: bigint];
  export interface OutputObject {
    vault: string;
    lockBps: bigint;
    holdBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalEvent {
  export type InputTuple = [
    vault: AddressLike,
    recipient: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [vault: string, recipient: string, amount: bigint];
  export interface OutputObject {
    vault: string;
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VaultWallet extends BaseContract {
  connect(runner?: ContractRunner | null): VaultWallet;
  waitForDeployment(): Promise<this>;

  interface: VaultWalletInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  availableBalance: TypedContractMethod<[], [bigint], "view">;

  claimUnlocked: TypedContractMethod<[], [void], "nonpayable">;

  currency: TypedContractMethod<[], [string], "view">;

  currentHoldBps: TypedContractMethod<[], [bigint], "view">;

  currentLockBps: TypedContractMethod<[], [bigint], "view">;

  currentSplits: TypedContractMethod<
    [arg0: BigNumberish],
    [[string, bigint] & { recipient: string; bps: bigint }],
    "view"
  >;

  getBalance: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        available: bigint;
        locked: bigint;
        total: bigint;
      }
    ],
    "view"
  >;

  getRouting: TypedContractMethod<
    [],
    [
      [IVaultWallet.SplitRecipientStructOutput[], bigint, bigint] & {
        splits: IVaultWallet.SplitRecipientStructOutput[];
        lockBps: bigint;
        holdBps: bigint;
      }
    ],
    "view"
  >;

  initialize: TypedContractMethod<
    [_owner: AddressLike, _taskEscrow: AddressLike, _currency: AddressLike],
    [void],
    "nonpayable"
  >;

  initialized: TypedContractMethod<[], [boolean], "view">;

  lockedBalance: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  receivePayment: TypedContractMethod<
    [amount: BigNumberish, taskId: BytesLike, payer: AddressLike],
    [void],
    "nonpayable"
  >;

  setRouting: TypedContractMethod<
    [
      splits: IVaultWallet.SplitRecipientStruct[],
      lockBps: BigNumberish,
      holdBps: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  taskEscrow: TypedContractMethod<[], [string], "view">;

  timeLocks: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, string] & {
        amount: bigint;
        unlockBlock: bigint;
        taskId: string;
      }
    ],
    "view"
  >;

  withdraw: TypedContractMethod<
    [amount: BigNumberish, recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "availableBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "claimUnlocked"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "currency"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "currentHoldBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "currentLockBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "currentSplits"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [[string, bigint] & { recipient: string; bps: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBalance"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        available: bigint;
        locked: bigint;
        total: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRouting"
  ): TypedContractMethod<
    [],
    [
      [IVaultWallet.SplitRecipientStructOutput[], bigint, bigint] & {
        splits: IVaultWallet.SplitRecipientStructOutput[];
        lockBps: bigint;
        holdBps: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [_owner: AddressLike, _taskEscrow: AddressLike, _currency: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "initialized"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "lockedBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "receivePayment"
  ): TypedContractMethod<
    [amount: BigNumberish, taskId: BytesLike, payer: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setRouting"
  ): TypedContractMethod<
    [
      splits: IVaultWallet.SplitRecipientStruct[],
      lockBps: BigNumberish,
      holdBps: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "taskEscrow"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "timeLocks"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, string] & {
        amount: bigint;
        unlockBlock: bigint;
        taskId: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [amount: BigNumberish, recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "PaymentProcessed"
  ): TypedContractEvent<
    PaymentProcessedEvent.InputTuple,
    PaymentProcessedEvent.OutputTuple,
    PaymentProcessedEvent.OutputObject
  >;
  getEvent(
    key: "RoutingUpdated"
  ): TypedContractEvent<
    RoutingUpdatedEvent.InputTuple,
    RoutingUpdatedEvent.OutputTuple,
    RoutingUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawal"
  ): TypedContractEvent<
    WithdrawalEvent.InputTuple,
    WithdrawalEvent.OutputTuple,
    WithdrawalEvent.OutputObject
  >;

  filters: {
    "PaymentProcessed(bytes32,uint256,uint256,uint256)": TypedContractEvent<
      PaymentProcessedEvent.InputTuple,
      PaymentProcessedEvent.OutputTuple,
      PaymentProcessedEvent.OutputObject
    >;
    PaymentProcessed: TypedContractEvent<
      PaymentProcessedEvent.InputTuple,
      PaymentProcessedEvent.OutputTuple,
      PaymentProcessedEvent.OutputObject
    >;

    "RoutingUpdated(address,uint16,uint16)": TypedContractEvent<
      RoutingUpdatedEvent.InputTuple,
      RoutingUpdatedEvent.OutputTuple,
      RoutingUpdatedEvent.OutputObject
    >;
    RoutingUpdated: TypedContractEvent<
      RoutingUpdatedEvent.InputTuple,
      RoutingUpdatedEvent.OutputTuple,
      RoutingUpdatedEvent.OutputObject
    >;

    "Withdrawal(address,address,uint256)": TypedContractEvent<
      WithdrawalEvent.InputTuple,
      WithdrawalEvent.OutputTuple,
      WithdrawalEvent.OutputObject
    >;
    Withdrawal: TypedContractEvent<
      WithdrawalEvent.InputTuple,
      WithdrawalEvent.OutputTuple,
      WithdrawalEvent.OutputObject
    >;
  };
}
