/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "AgentRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AgentRegistry__factory>;
    getContractFactory(
      name: "VaultWallet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.VaultWallet__factory>;
    getContractFactory(
      name: "DisputeResolver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DisputeResolver__factory>;
    getContractFactory(
      name: "ITaskEscrowDispute",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ITaskEscrowDispute__factory>;
    getContractFactory(
      name: "IAgentRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAgentRegistry__factory>;
    getContractFactory(
      name: "INegotiationEngine",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.INegotiationEngine__factory>;
    getContractFactory(
      name: "ITaskEscrow",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ITaskEscrow__factory>;
    getContractFactory(
      name: "IVaultWallet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IVaultWallet__factory>;
    getContractFactory(
      name: "NegotiationEngine",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.NegotiationEngine__factory>;
    getContractFactory(
      name: "ReputationBondManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ReputationBondManager__factory>;
    getContractFactory(
      name: "IDisputeResolver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDisputeResolver__factory>;
    getContractFactory(
      name: "TaskEscrow",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TaskEscrow__factory>;

    getContractAt(
      name: "AgentRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AgentRegistry>;
    getContractAt(
      name: "VaultWallet",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.VaultWallet>;
    getContractAt(
      name: "DisputeResolver",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.DisputeResolver>;
    getContractAt(
      name: "ITaskEscrowDispute",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ITaskEscrowDispute>;
    getContractAt(
      name: "IAgentRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAgentRegistry>;
    getContractAt(
      name: "INegotiationEngine",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.INegotiationEngine>;
    getContractAt(
      name: "ITaskEscrow",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ITaskEscrow>;
    getContractAt(
      name: "IVaultWallet",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IVaultWallet>;
    getContractAt(
      name: "NegotiationEngine",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.NegotiationEngine>;
    getContractAt(
      name: "ReputationBondManager",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ReputationBondManager>;
    getContractAt(
      name: "IDisputeResolver",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IDisputeResolver>;
    getContractAt(
      name: "TaskEscrow",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TaskEscrow>;

    deployContract(
      name: "AgentRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AgentRegistry>;
    deployContract(
      name: "VaultWallet",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VaultWallet>;
    deployContract(
      name: "DisputeResolver",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DisputeResolver>;
    deployContract(
      name: "ITaskEscrowDispute",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ITaskEscrowDispute>;
    deployContract(
      name: "IAgentRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAgentRegistry>;
    deployContract(
      name: "INegotiationEngine",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.INegotiationEngine>;
    deployContract(
      name: "ITaskEscrow",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ITaskEscrow>;
    deployContract(
      name: "IVaultWallet",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVaultWallet>;
    deployContract(
      name: "NegotiationEngine",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.NegotiationEngine>;
    deployContract(
      name: "ReputationBondManager",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReputationBondManager>;
    deployContract(
      name: "IDisputeResolver",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDisputeResolver>;
    deployContract(
      name: "TaskEscrow",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TaskEscrow>;

    deployContract(
      name: "AgentRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AgentRegistry>;
    deployContract(
      name: "VaultWallet",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VaultWallet>;
    deployContract(
      name: "DisputeResolver",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DisputeResolver>;
    deployContract(
      name: "ITaskEscrowDispute",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ITaskEscrowDispute>;
    deployContract(
      name: "IAgentRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAgentRegistry>;
    deployContract(
      name: "INegotiationEngine",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.INegotiationEngine>;
    deployContract(
      name: "ITaskEscrow",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ITaskEscrow>;
    deployContract(
      name: "IVaultWallet",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVaultWallet>;
    deployContract(
      name: "NegotiationEngine",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.NegotiationEngine>;
    deployContract(
      name: "ReputationBondManager",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReputationBondManager>;
    deployContract(
      name: "IDisputeResolver",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDisputeResolver>;
    deployContract(
      name: "TaskEscrow",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TaskEscrow>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
