/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace INegotiationEngine {
  export type CounterBidStruct = {
    price: BigNumberish;
    by: AddressLike;
    at: BigNumberish;
  };

  export type CounterBidStructOutput = [
    price: bigint,
    by: string,
    at: bigint
  ] & { price: bigint; by: string; at: bigint };

  export type BidStruct = {
    bidId: BytesLike;
    taskSpecCID: string;
    initiator: AddressLike;
    targetAgent: AddressLike;
    price: BigNumberish;
    ttlBlocks: BigNumberish;
    state: BigNumberish;
    counterHistory: INegotiationEngine.CounterBidStruct[];
    createdAt: BigNumberish;
  };

  export type BidStructOutput = [
    bidId: string,
    taskSpecCID: string,
    initiator: string,
    targetAgent: string,
    price: bigint,
    ttlBlocks: bigint,
    state: bigint,
    counterHistory: INegotiationEngine.CounterBidStructOutput[],
    createdAt: bigint
  ] & {
    bidId: string;
    taskSpecCID: string;
    initiator: string;
    targetAgent: string;
    price: bigint;
    ttlBlocks: bigint;
    state: bigint;
    counterHistory: INegotiationEngine.CounterBidStructOutput[];
    createdAt: bigint;
  };
}

export interface NegotiationEngineInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptBid"
      | "agentBids"
      | "allBidIds"
      | "bids"
      | "cancelBid"
      | "counterBid"
      | "getAgentBids"
      | "getAllBidIds"
      | "getBid"
      | "owner"
      | "registry"
      | "setTaskEscrow"
      | "submitBid"
      | "taskEscrow"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BidAccepted"
      | "BidCancelled"
      | "BidCountered"
      | "BidSubmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptBid",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "agentBids",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "allBidIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "bids", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "cancelBid",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "counterBid",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentBids",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllBidIds",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getBid", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setTaskEscrow",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitBid",
    values: [string, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "taskEscrow",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "acceptBid", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "agentBids", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "allBidIds", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "bids", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cancelBid", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "counterBid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAgentBids",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllBidIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBid", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setTaskEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "submitBid", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "taskEscrow", data: BytesLike): Result;
}

export namespace BidAcceptedEvent {
  export type InputTuple = [
    bidId: BytesLike,
    agreedPrice: BigNumberish,
    escrowId: BytesLike
  ];
  export type OutputTuple = [
    bidId: string,
    agreedPrice: bigint,
    escrowId: string
  ];
  export interface OutputObject {
    bidId: string;
    agreedPrice: bigint;
    escrowId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BidCancelledEvent {
  export type InputTuple = [bidId: BytesLike];
  export type OutputTuple = [bidId: string];
  export interface OutputObject {
    bidId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BidCounteredEvent {
  export type InputTuple = [
    bidId: BytesLike,
    by: AddressLike,
    newPrice: BigNumberish
  ];
  export type OutputTuple = [bidId: string, by: string, newPrice: bigint];
  export interface OutputObject {
    bidId: string;
    by: string;
    newPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BidSubmittedEvent {
  export type InputTuple = [
    bidId: BytesLike,
    initiator: AddressLike,
    targetAgent: AddressLike,
    taskSpecCID: string,
    price: BigNumberish,
    ttl: BigNumberish
  ];
  export type OutputTuple = [
    bidId: string,
    initiator: string,
    targetAgent: string,
    taskSpecCID: string,
    price: bigint,
    ttl: bigint
  ];
  export interface OutputObject {
    bidId: string;
    initiator: string;
    targetAgent: string;
    taskSpecCID: string;
    price: bigint;
    ttl: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface NegotiationEngine extends BaseContract {
  connect(runner?: ContractRunner | null): NegotiationEngine;
  waitForDeployment(): Promise<this>;

  interface: NegotiationEngineInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptBid: TypedContractMethod<[bidId: BytesLike], [void], "nonpayable">;

  agentBids: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  allBidIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  bids: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, string, bigint, bigint, bigint, bigint] & {
        bidId: string;
        taskSpecCID: string;
        initiator: string;
        targetAgent: string;
        price: bigint;
        ttlBlocks: bigint;
        state: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  cancelBid: TypedContractMethod<[bidId: BytesLike], [void], "nonpayable">;

  counterBid: TypedContractMethod<
    [bidId: BytesLike, newPrice: BigNumberish],
    [void],
    "nonpayable"
  >;

  getAgentBids: TypedContractMethod<[agent: AddressLike], [string[]], "view">;

  getAllBidIds: TypedContractMethod<[], [string[]], "view">;

  getBid: TypedContractMethod<
    [bidId: BytesLike],
    [INegotiationEngine.BidStructOutput],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  registry: TypedContractMethod<[], [string], "view">;

  setTaskEscrow: TypedContractMethod<
    [_taskEscrow: AddressLike],
    [void],
    "nonpayable"
  >;

  submitBid: TypedContractMethod<
    [
      taskSpecCID: string,
      targetAgent: AddressLike,
      price: BigNumberish,
      ttlBlocks: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  taskEscrow: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptBid"
  ): TypedContractMethod<[bidId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "agentBids"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "allBidIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "bids"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, string, bigint, bigint, bigint, bigint] & {
        bidId: string;
        taskSpecCID: string;
        initiator: string;
        targetAgent: string;
        price: bigint;
        ttlBlocks: bigint;
        state: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "cancelBid"
  ): TypedContractMethod<[bidId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "counterBid"
  ): TypedContractMethod<
    [bidId: BytesLike, newPrice: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAgentBids"
  ): TypedContractMethod<[agent: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getAllBidIds"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getBid"
  ): TypedContractMethod<
    [bidId: BytesLike],
    [INegotiationEngine.BidStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setTaskEscrow"
  ): TypedContractMethod<[_taskEscrow: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitBid"
  ): TypedContractMethod<
    [
      taskSpecCID: string,
      targetAgent: AddressLike,
      price: BigNumberish,
      ttlBlocks: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "taskEscrow"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "BidAccepted"
  ): TypedContractEvent<
    BidAcceptedEvent.InputTuple,
    BidAcceptedEvent.OutputTuple,
    BidAcceptedEvent.OutputObject
  >;
  getEvent(
    key: "BidCancelled"
  ): TypedContractEvent<
    BidCancelledEvent.InputTuple,
    BidCancelledEvent.OutputTuple,
    BidCancelledEvent.OutputObject
  >;
  getEvent(
    key: "BidCountered"
  ): TypedContractEvent<
    BidCounteredEvent.InputTuple,
    BidCounteredEvent.OutputTuple,
    BidCounteredEvent.OutputObject
  >;
  getEvent(
    key: "BidSubmitted"
  ): TypedContractEvent<
    BidSubmittedEvent.InputTuple,
    BidSubmittedEvent.OutputTuple,
    BidSubmittedEvent.OutputObject
  >;

  filters: {
    "BidAccepted(bytes32,uint256,bytes32)": TypedContractEvent<
      BidAcceptedEvent.InputTuple,
      BidAcceptedEvent.OutputTuple,
      BidAcceptedEvent.OutputObject
    >;
    BidAccepted: TypedContractEvent<
      BidAcceptedEvent.InputTuple,
      BidAcceptedEvent.OutputTuple,
      BidAcceptedEvent.OutputObject
    >;

    "BidCancelled(bytes32)": TypedContractEvent<
      BidCancelledEvent.InputTuple,
      BidCancelledEvent.OutputTuple,
      BidCancelledEvent.OutputObject
    >;
    BidCancelled: TypedContractEvent<
      BidCancelledEvent.InputTuple,
      BidCancelledEvent.OutputTuple,
      BidCancelledEvent.OutputObject
    >;

    "BidCountered(bytes32,address,uint256)": TypedContractEvent<
      BidCounteredEvent.InputTuple,
      BidCounteredEvent.OutputTuple,
      BidCounteredEvent.OutputObject
    >;
    BidCountered: TypedContractEvent<
      BidCounteredEvent.InputTuple,
      BidCounteredEvent.OutputTuple,
      BidCounteredEvent.OutputObject
    >;

    "BidSubmitted(bytes32,address,address,string,uint256,uint256)": TypedContractEvent<
      BidSubmittedEvent.InputTuple,
      BidSubmittedEvent.OutputTuple,
      BidSubmittedEvent.OutputObject
    >;
    BidSubmitted: TypedContractEvent<
      BidSubmittedEvent.InputTuple,
      BidSubmittedEvent.OutputTuple,
      BidSubmittedEvent.OutputObject
    >;
  };
}
