/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ReputationBondManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "calculateRequiredBond"
      | "disputeResolver"
      | "owner"
      | "registry"
      | "setDisputeResolver"
      | "slashBond"
      | "verifyBondSufficiency"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "BondSlashed"): EventFragment;

  encodeFunctionData(
    functionFragment: "calculateRequiredBond",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "disputeResolver",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setDisputeResolver",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "slashBond",
    values: [AddressLike, BigNumberish, BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyBondSufficiency",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "calculateRequiredBond",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disputeResolver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setDisputeResolver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "slashBond", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifyBondSufficiency",
    data: BytesLike
  ): Result;
}

export namespace BondSlashedEvent {
  export type InputTuple = [
    agentId: AddressLike,
    slashedAmount: BigNumberish,
    taskId: BytesLike
  ];
  export type OutputTuple = [
    agentId: string,
    slashedAmount: bigint,
    taskId: string
  ];
  export interface OutputObject {
    agentId: string;
    slashedAmount: bigint;
    taskId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ReputationBondManager extends BaseContract {
  connect(runner?: ContractRunner | null): ReputationBondManager;
  waitForDeployment(): Promise<this>;

  interface: ReputationBondManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  calculateRequiredBond: TypedContractMethod<
    [taskValueUsdc: BigNumberish],
    [bigint],
    "view"
  >;

  disputeResolver: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  registry: TypedContractMethod<[], [string], "view">;

  setDisputeResolver: TypedContractMethod<
    [_disputeResolver: AddressLike],
    [void],
    "nonpayable"
  >;

  slashBond: TypedContractMethod<
    [
      agentId: AddressLike,
      amount: BigNumberish,
      taskId: BytesLike,
      recipient: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  verifyBondSufficiency: TypedContractMethod<
    [agentId: AddressLike, taskValueUsdc: BigNumberish],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "calculateRequiredBond"
  ): TypedContractMethod<[taskValueUsdc: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "disputeResolver"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setDisputeResolver"
  ): TypedContractMethod<[_disputeResolver: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "slashBond"
  ): TypedContractMethod<
    [
      agentId: AddressLike,
      amount: BigNumberish,
      taskId: BytesLike,
      recipient: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyBondSufficiency"
  ): TypedContractMethod<
    [agentId: AddressLike, taskValueUsdc: BigNumberish],
    [boolean],
    "view"
  >;

  getEvent(
    key: "BondSlashed"
  ): TypedContractEvent<
    BondSlashedEvent.InputTuple,
    BondSlashedEvent.OutputTuple,
    BondSlashedEvent.OutputObject
  >;

  filters: {
    "BondSlashed(address,uint256,bytes32)": TypedContractEvent<
      BondSlashedEvent.InputTuple,
      BondSlashedEvent.OutputTuple,
      BondSlashedEvent.OutputObject
    >;
    BondSlashed: TypedContractEvent<
      BondSlashedEvent.InputTuple,
      BondSlashedEvent.OutputTuple,
      BondSlashedEvent.OutputObject
    >;
  };
}
