/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ITaskEscrowDispute,
  ITaskEscrowDisputeInterface,
} from "../../DisputeResolver.sol/ITaskEscrowDispute";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "escrowId",
        type: "bytes32",
      },
      {
        internalType: "uint8",
        name: "resolutionOutcome",
        type: "uint8",
      },
    ],
    name: "resolveDispute",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ITaskEscrowDispute__factory {
  static readonly abi = _abi;
  static createInterface(): ITaskEscrowDisputeInterface {
    return new Interface(_abi) as ITaskEscrowDisputeInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ITaskEscrowDispute {
    return new Contract(address, _abi, runner) as unknown as ITaskEscrowDispute;
  }
}
